stages:
  - install_dependencies
  - create_required_files
  - build_backend
  - build_docs
  - build_frontend
  - create_docker

variables:
  GIT_STRATEGY: fetch
  GIT_CLEAN_FLAGS: "" 

cache:
  key: shared-node
  paths:
    - backend/api/node_modules
    - frontend/node_modules

install_dependencies:
  stage: install_dependencies
  script:
    - cd backend/api && npm install
    - cd ../../frontend && npm install
    #- npm run buildInitial INSTALL_NPM_DEPENDENCIES

create_required_files:
  stage: create_required_files
  script:
    - npm run buildInitial CREATE_CONFIG_AND_ENV CREATE_CERTS CREATE_TEMPLATES CREATE_LOCAL_USERS PROD_CREATE_ENV

build_backend:
  stage: build_backend
  script:
    - cd backend/api && npm install
    - cd ../../frontend && npm install
    - cd /
    - npm run buildInitial PROD_BUILD_BACKEND

build_docs:
  stage: build_docs
  script:
    - npm run buildInitial PROD_BUILD_DOCS

build_frontend:
  stage: build_frontend
  script:
    - npm run buildInitial PROD_BUILD_FRONTEND

create_docker:
  stage: create_docker
  script:
    - npm run buildInitial PROD_START_DOCKER
