stages:
  - install_dependencies
  - create_required_files
  - build_backend
  - build_docs
  - build_frontend
  - create_docker
#  - check_services

variables:
  GIT_STRATEGY: fetch
  GIT_CLEAN_FLAGS: "" 

cache:
  key: 
    files:
      - backend/api/package-lock.json
      - frontend/package-lock.json
  paths:
    - backend/api/node_modules
    - frontend/node_modules

install_dependencies:
  stage: install_dependencies
  script:
    - cd backend/api && npm install
    - cd ../../frontend && npm install
    #- npm run buildInitial INSTALL_NPM_DEPENDENCIES
  #artifacts:
  #  paths:
  #    - backend/api/node_modules
  #    - frontend/node_modules

create_required_files:
  stage: create_required_files
  script:
    #- npm run buildInitial CREATE_CONFIG_AND_ENV CREATE_CERTS CREATE_TEMPLATES CREATE_LOCAL_USERS PROD_CREATE_ENV
    - ls -la /home/gitlab-runner/envFiles/
    - COPY_PATH=/home/gitlab-runner/envFiles npm run buildInitial CREATE_CERTS PROD_COPY_FILES
  artifacts:
    paths:
      - backend/api/src/certs
      - backend/api/src
      # TODO staticdata instead? 
      - backend/api/src/staticdate
      - backend/api/environment
      - frontend/src/environments
      - .env

build_backend:
  stage: build_backend
  dependencies:
    - install_dependencies
    - create_required_files
  script:
    - cd backend/api && npm run generateDB && cd ../../
    - npm run buildInitial PROD_BUILD_BACKEND
  artifacts:
    paths:
      - backend/api/dist

build_docs:
  stage: build_docs
  dependencies: []
  script:
    - npm run buildInitial PROD_BUILD_DOCS
  artifacts:
    paths:
      - server/app/docs

build_frontend:
  stage: build_frontend
  dependencies:
    - install_dependencies
    - create_required_files
  script:
    - npm run buildInitial PROD_BUILD_FRONTEND
  artifacts:
    paths:
      - server/app/browser

create_docker:
  stage: create_docker
  dependencies:
    - install_dependencies
    - create_required_files
    - build_backend
    - build_docs
    - build_frontend
  script:
    - npm run buildInitial PROD_START_DOCKER
    - sleep 40
    - npm run buildInitial CHECK_ALL

# check_services:
#   stage: check_services
#   dependencies:
#     - install_dependencies
#     - create_required_files
#     - build_backend
#     - build_docs
#     - build_frontend
#     - create_docker
#   script:
#     # - npm run buildInitial ...
#     - npm run buildInitial CHECK_API_PYTHON CHECK_API_NODE